# Generated by Django 5.2.3 on 2025-06-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotWheelsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('series', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('image', models.URLField()),
            ],
        ),
    ]
